### ISSUE TITLE
kdepim/kontact anstatt evolution

### ISSUE THREAD

**Issue by horazont** [fsfw-dresden/usb-live-linux#1]
Da der Rest des Systems auch KDE verwendet, würde ich für `kontact`, `kdepim` und `kdepim-addons` anstatt `evolution` stimmen.

Ich kann leider nicht testen weil das ganze bei mir aus $gründen nicht baut, wahrscheinlich stretch vs. jessie Probleme.

**Comment by gerdg-dd** [comment]
` kdepim-addons `  - erst ab stretch verfügbar 

Hinweis: baut jetzt auch auf stretch

**Comment by Nos-** [comment]
Ich habe diese Änderung in meinem Fork des Repos bereits umgesetzt. Pull-Request erfolgt, sobald ich das LiveImage erfolgreich gebaut habe. (Wäre schön, wenn dann schon mein voriger Pullrequest #6 entweder angenommen oder (samt Begründung) abgewiesen wäre.)

**Comment by Nos-** [comment]
So, ich hab nun eine neue Variante erfolgreich getestet und würde mich über kontact statt Evolution freuen (Ich habs schon mal in der Paketliste vorbereitet). Siehe meinen neuen Pullrequest #7

**Comment by gerdg-dd** [comment]
kontact benötigt einen Datenbankserver.  --> akonadi   - sqlite  postgresql oder mysql .
Was benutzt ihr ? akonadi-backend-sqlite  für den Stick  ok . 
Andere Datenbank, was bringt das auf dem Stick ?
MySQL meide ich wo es geht, da ich nicht mehrere Datenbankserver als notwendig  auf meinem System haben möchte. 
Meine wahl für die Installation Postgresql.

kontact Anbindung an einen  Serverdienst (z.B. radical) für CalDAV ( Addressen) und iCAL ( Termine und Aufgaben ) zwecks syncronisation mit Android (ohne Google zu benutzen) hab ich auf die schnelle nicht gefunden.
Geht das ?

Hat jemand schon mal mit sqlite getestet.?
 
VG Gerd

**Comment by Nos-** [comment]
Hmm, Sqlite wäre auch meine Wahl für den Stick.

Wegen Handy-Sync habe ich leider aiuch noch nichts gefunden. Meine Wahl wäre 'nen Nextcloud oder so. Aber ob das auf dem Stick wirklich praktisch ist?

**Comment by gerdg-dd** [comment]
Für CalDAV ( Addressen) und iCAL ( Termine und Aufgaben ) benutze ich als server "radical" .
Die Addressen, Termine, Aufgaben werden bei mir in "evolution" eingebunden.
Syncronisation mit Android über DAVdroid (f-droid.org) und dem localen WLan.
Die Nutzung der Addressen/Telefonnumern aus "evolution", funktioniert mittels RogerRouter auch für die Telefon und Faxunterstützung mit der Fritzbox.

Über "radical" kann durch entsprechende Nutzereinrichtung auch Gruppenkalender, -adressbücher etc. genutzt werden.  

Das "kontact" aus e-mails Termine und Aufgaben erstellen kann setze ich mal vorraus. 

Netxcloude etc. find ich an der Stelle ist einfoch zu groß/komplex.

**Comment by Nos-** [comment]
Na, falls du dich mit radical auskennst und es mit auf dem Stick haben möchtest, schreib es bitte mit in die Liste. Ich baue die dann gerne nochmal und lade sie dann wieder hoch.

**Comment by Nos-** [comment]
Aktuell sind Kontact (sowie Icedove) und Sqlite installiert. Wegen Akonadi, Radical etc. habe ich nichts gemacht.

Falls es hierzu bereits etwas erfolgreich getestetes gibt, sollte es **jetzt** in den Masterbranch gemerged werden! Sonst kommt es nicht mehr mit auf den Stick.
