### ISSUE TITLE
Firefox Registrierung Abschalten

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#10]
Wenn man firefox das erste Mal lädt eine Webseite die zur Registrierung bei Mozilla auffordert. -> Verwirrungspotential -> Möglichst Vermeiden!

- [ ] Wenn die Persistenz-Geschichte wieder geht, rausfinden wie man das verhindern kann.
- [ ] Über einen Hook oder `config/includes.chroot/...` lösen

**Comment by gerdg-dd** [comment]
Persistenz-Geschichte wieder geht ?? - wo klemmts den  ?

**Comment by Nos-** [comment]
Naja, für die Persistenzgeschichte wäre es wichtig, das der Usb-Stick funktioniert. Bei mir bootet er leider nicht.

**Comment by gerdg-dd** [comment]
bootet nicht !! - ist leider nicht sehr hilfreich.

Was hast du aus meiner letzten e-mail umgesetzt / geprüft ?
Mit welcher Version hast du das Image gebaut ?

Ausgabe von :
   `$ cd ..../FSFW-Uni-Stick`
   `$ ls -1 binary/live/[vi]*`

binary/live/initrd.img
binary/live/initrd.img-3.16.0-4-amd64
binary/live/vmlinuz
binary/live/vmlinuz-3.16.0-4-amd64

??

**Comment by Nos-** [comment]
> Was hast du aus meiner letzten e-mail umgesetzt / geprüft ?

Ich nutze den Stand vom 5.10. des Hauptrepos (den ich mir in mein repo gezogen habe).

```
FSFW-Uni-Stick$ ls -l binary/
drwxr-xr-x 1 root root     8 Okt  9 23:03 boot
lrwxrwxrwx 1 root root    11 Okt  9 23:03 initrd.img -> initrd.img*
drwxr-xr-x 1 root root     0 Okt  9 23:03 isolinux
drwxr-xr-x 1 root root   252 Okt  9 23:03 live
-rw-r--r-- 1 root root 18817 Okt  9 23:03 md5sum.txt
lrwxrwxrwx 1 root root     8 Okt  9 23:03 vmlinuz -> vmlinuz*
```
Sieht nicht gut aus!

> Mit welcher Version hast du das Image gebaut ?

Version: 1:20151215
Auf einem Debian testing (stretch)

> Ausgabe von :
> $ cd ..../FSFW-Uni-Stick
> $ ls -1 binary/live/[vi]*

```
FSFW-Uni-Stick$ ls -1 binary/live/[vi]*
binary/live/initrd.img-3.16.0-4-amd64
binary/live/vmlinuz-3.16.0-4-amd64

```

**Comment by gerdg-dd** [comment]
da sind wohl die links im falschen Verzeichnis 
die gehören nach binary/live -- siehe ausgabe wie oben

**Comment by Nos-** [comment]
Naja, im build.log heißt es:

```
P: Begin executing hooks...
 -- hotfix for Debian stretch -- 
 ERROR: config/binary nicht lesbar 

Aktuelles Arbeitsverzeichnis: 
/home/norman/Projekte/usb-live-linux/FSFW-Uni-Stick/binary
../config/hooks/normal/1000-stretch-hotfix.hook.binary: 38: cd: can't cd to binary/live

```

Mal sehen, ob ich am Nachmittag dazu komme, da etwas zu machen.

**Comment by gerdg-dd** [comment]
Debian: du bist in der Gruppe sudo ?
  `# addgroup "user" sudo`
eventell neu einlogen
  `sudo lb build`    ?? ausgeführt - sollte eigentlich funktionieren

**Comment by gerdg-dd** [comment]
übrigens solltest du schon mal erwähnen, das du 
" 1000-stretch-boot-hotfix.hook.binary "
umgeschreiben hast  und nicht nur melden "bootet nicht" !.

schau dir das noch mal genau an

**Comment by vv01f** [comment]
wurde durch einmal öffnen und schließen gelöst

**Comment by cknoll** [comment]
.mozilla-Verzeichnis welches wir wegen der Bookmarks ohnehin mit ausliefern klärt das Firefox-Problem..
