### ISSUE TITLE
Aktuelles Jupyter/IPython installieren

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#11]
- [x] Notwendige Pakete rausfinden
- [x] Install-Skript schreiben, welches pip3 aufruft
- [x] Ausführung des Skripts erreichen
- [x] NB-Verzeichnis festlegen
- [x] Illustratives Beispiel einfügen
- [ ] Browser mit Verknüpfung starten

**Comment by cknoll** [comment]
im Branch ck/aktuelles_python funktioniert es rudimentär. Weitere Anpassungen sind aber nötig

**Comment by Nos-** [comment]
Beim Durchsehen des Buildlogs fiel mir eine Fehlermeldung wegen einem angeblich fehlenden `zmq` (bzw. `libzmq` und `pyzmq`) auf. Vielleicht würde es helfen, das Paket `python-zmq` mit in die Sw-Liste aufzunehmen.

**Comment by cknoll** [comment]
Das sollte inzwischen behoben sein.
