### ISSUE TITLE
FSFW-Uni-Stick mit Debian 9.0 stretch

### ISSUE THREAD

**Issue by gerdg-dd** [fsfw-dresden/usb-live-linux#110]
momentan bin ich am Testen --> branch feature_gg_multiconfig

    Image baut und bootet KDE_stretch_amd64
    der Vorschlag task-kde-desktop bringt derzeit

-- ohne recommends

    Image ohne funktionierenden Fenstermanger
    2880045056 Sep 15 15:38 FSFW-Uni-Stick_417u__feature_gg_multiconfig__KDE_stretch-amd64.hybrid.iso

-- mit recommends

    Image mit funktionierendem Fenstermanger
    4831174656 Sep 15 19:11 FSFW-Uni-Stick_417u__feature_gg_multiconfig__KDE_stretch-amd64.hybrid.iso

-- User Einstellungen müssen komplett überarbeitet werden, da passt derzeit nicht mehr viel

Es gibt also noch viele Punkte zu überarbeiten

**Comment by gerdg-dd** [comment]
momentan bin ich am Testen --> branch feature_gg_multiconfig
- Image baut und bootet  KDE_stretch_amd64
der Vorschlag task-kde-desktop bringt derzeit

-- ohne recommends 
  -  Image ohne funktionierenden Fenstermanger
  - 2880045056 Sep 15 15:38 FSFW-Uni-Stick_417u__feature_gg_multiconfig__KDE_stretch-amd64.hybrid.iso

-- mit recommends 
  - Image mit funktionierendem Fenstermanger
  - 4831174656 Sep 15 19:11 FSFW-Uni-Stick_417u__feature_gg_multiconfig__KDE_stretch-amd64.hybrid.iso

-- User Einstellungen müssen komplett überarbeitet werden, da passt derzeit nicht mehr viel

Es gibt also noch viele Punkte zu überarbeiten

**Comment by gerdg-dd** [comment]
Image erstellen

    $ git pull
    $ cd ..../FSFW-Uni-Stick
    $ ./fsfw-uni-stick_build.sh FSFW-Uni-Stick_KDE_stretch_amd64

erstellte Images  befinden sich in ../images

**Comment by Nos-** [comment]
Hmm, ich habe heute die Branches develop und feature_gg_multiconfig testweise auf meinem Debian stable gebaut und ausprobiert (Das Iso-Image nimmt bei mir jeweils 2,5 GB). Das KDE ist im KVM mit 2 GB Ram fürs Gastsystem bedienbar. Allerdings bin ich ein wenig verwundert, das ein 3.16er-Kernel verwendet wird, was erher für Jessie und nicht Stretch spricht. 

Mein Vorgehen (lt. Doku):

> $ ./fsfw-uni-stick_build.sh
> 
> # ...einige Zeit später...
> $ kvm -m 2048 -cdrom images/FSFW-Uni-Stick_411q__develop__jessie-amd64.hybrid.iso
> $ kvm -m 2048 -cdrom images/FSFW-Uni-Stick_411q__develop__jessie-amd64.hybrid.iso
>

**Comment by Nos-** [comment]
So, mit 

`$ ./fsfw-uni-stick_build.sh FSFW-Uni-Stick_KDE_stretch_amd64`

baut und bootet es zwar, es ist aber noch einiges an Konfigarbeit zu tun.
Der Kernel ist nun mit Vers. 4.9 auch recht aktuell. Größe der Iso-Imagedatei: 2,7 GB

Ich denke mal, gute Arbeit bisher!

**Comment by gerdg-dd** [comment]
config/FSFW-Uni-Stick_KDE_stretch_amd64 ist jetzt default im branch develop
