### ISSUE TITLE
Symbole auf dem Desktop anzeigen

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#12]
- [x] index.html (unsere Doku)
- [x] Home-Verzeichnis -> Dolphin Dateimanager
- [ ] LibreOffice
- [ ] TexStudio (mit unserer Vorlage)
- [ ] Ordner mit Verknüpfungen zu weiteren nützlichen Programmen
- [x] Terminal
- [x] Folder View, keine Widgets
- [x] Config f. Hintergrundbild
- [ ] Vorgegebener Nutzer bekommt Vorgaben sauber angezeigt
- [x] /etc/skel für neue User vorbereiten

**Comment by Nos-** [comment]
So siehts aktuell aus (sobald ich die Änderungen in den Branchj hier gepusht habe):

![kde-desktop_mit_icons_10_10_2016_10_04_42](https://cloud.githubusercontent.com/assets/6155874/19230002/01076f8a-8ed2-11e6-8b6d-23b10400c7e6.png)

**Die Frage ist nun**

1. wollen wir eigenständige Programmicons
  * wie beim TeX-Studio-Icon zu sehen, ist das vermutlich noch nicht das optimale
2. wollen wir die Icons in einem Ordnerwidget
  * hier verhalten sich die Icons wie Dateien (bzw. Ordner), was ich von der Usability her wesentlich besser finde

**Comment by Nos-** [comment]
Hmm, irgendetwas ist noch. ich bekomme nur noch folgende Fehlermeldung:

`Call to lnusertemp failed (temporary directories full?) Check your installation.`

**Comment by cknoll** [comment]
im ausgelieferten Master funktioniert es

**Comment by Nos-** [comment]
Hmm, habs gerade nochmal getestet und die Desktopsymbole (sowie auch unser FSFW-Hintergrundbild) sind wieder fort. (Nur der Webbrowser öffnet sich beim Login automatisch)

![fsfw-unistick_desktop_2016-10-26](https://cloud.githubusercontent.com/assets/6155874/19720860/2fc1b65a-9b70-11e6-841f-7aa90e151961.png)

**Comment by cknoll** [comment]
gleiches Verhalten bei mir.

Die relevante Dateien sind glaube ich:


~/.kde/share/config/plasma-desktop-appletsrc
~/.kde/share/config/plasma-desktoprc

aber was die Einträge darin genau bedeuten, weiß ich nicht.


wurden sie im Repo seit dem letzen funktionierenden Stand nicht
verändert. Wenn man mit kdiff3 die Datei in
~/aux_files/home-dir/.../plasma-desktop-appletsrc mit der in ~/...
vergleicht, stellt man fest:

Der Pfad zum richtigen Hintergrundbild steht in beiden drin, aber in der
~/... Version steht eben zusätzlich noch ein anderes ("Elrun") drin.

Wie die Zusatzzeilen da rein kommen, weiß ich auch nicht.

**Comment by cknoll** [comment]
Eventuell ist das hier relevant:

http://askubuntu.com/questions/588590/how-to-change-default-wallpaper-in-kde

**Comment by cknoll** [comment]
gleiches Verhalten bei mir.

Die relevante Dateien sind glaube ich:


~/.kde/share/config/plasma-desktop-appletsrc
~/.kde/share/config/plasma-desktoprc

aber was die Einträge darin genau bedeuten, weiß ich nicht.


wurden sie im Repo seit dem letzen funktionierenden Stand nicht
verändert. Wenn man mit kdiff3 die Datei in
~/aux_files/home-dir/.../plasma-desktop-appletsrc mit der in ~/...
vergleicht, stellt man fest:

Der Pfad zum richtigen Hintergrundbild steht in beiden drin, aber in der
~/... Version steht eben zusätzlich noch ein anderes ("Elrun") drin.

Wie die Zusatzzeilen da rein kommen, weiß ich auch nicht.

**Comment by Nos-** [comment]
Statt KDiff hilft bei mir auch ein Git-Versionieren des Home.

**Comment by cknoll** [comment]
Vermutlich ist es das beste, wenn wir jemanden fragen. Ich versuche mal rauszufinden, ob wir Dresdner KDE-Entwickler finden.

**Comment by cknoll** [comment]
Ein wichtiges Paket könnte folgendes sein:

kde-runtime-data: /usr/share/kde4/apps/desktoptheme/default/metadata.desktop

**Comment by s72785** [comment]
fundstelle https://forum.kde.org/viewtopic.php?t=25439

**Comment by gerdg-dd** [comment]
funktioniert bei mir mit gebautem Image FSFW-Uni-Stick_96n_jessie-amd64.hybrid.iso
--> würde ich als erledigt betrachten -- https://github.com/fsfw-dresden/usb-live-linux/commit/db26de8dc447f3fdcf2f84870562034d1dfdaa93 
--> schließen ? oder andere Meinungen

**Comment by cknoll** [comment]
@gerdg-dd Kannst Du hier noch kurz schreiben, was jetzt die Lösung war?

**Comment by gerdg-dd** [comment]
config geht nur  $home/.kde/share/config/plasma-desktop-appletsrc 
-  diese config wird falls nicht korrekt immer automatisch überschrieben oder neu erstellt

**Comment by cknoll** [comment]
Zur letzten Frage: ich wäre für "alles".

Allgemein, habe es gerade getestet. Bild und Symbole funktionieren. Sehr gut!


Verbleibende Probleme:
[ ] Symbole brauchen Berechtigung 755 sonst kommt ein Ausrufezeichen und eine nervige Abfrage beim ersten Klicken.
[ ] einige Elemente der manulellen Konfiguration fehlen (noch).Tastenkombinationen, jupyter, zim, texstudio, bashrc. Am besten wir telefonieren nochmal.

**Comment by Nos-** [comment]
Hallo, ich werds dann auch nochmal testen.

Anstatt Daten redundant vorzuhalten halte ich es für sinnvoll mit (Sym-)Links zu arbeiten. Wie seht ihr das?

**Comment by Nos-** [comment]
Hmm, wenn es denn funzt, bitte mal den Pullrequest #61 ansehen.

**Comment by Nos-** [comment]
So, habe den aktuellen Stand (FSFW-Uni-Stick_100a_jessie-amd64.hybrid.iso vom master-Branch) gerade gebaut und es scheint keine Konfig übernommen wurden zu sein. Weder Desktopsymbole, Hintergrundbild noch der Autostart vom Firefox (der übrigens wieder mit einer Registrierungsseite nervte).

Meine Buildumgebung: Debian stretch

**Comment by cknoll** [comment]
@Nos- Das Problem ist bekannt. Die Lösung liegt zur Zeit noch ein einem separaten Branch (ck_user-config). Ich baue ihn demnächst kompatibel zu Master.

Bezüglich #61: Das gehört m.E. nicht in dieses Issue. Ich schreibe dort noch einen Kommentar.

**Comment by gerdg-dd** [comment]
@Nos- mit FSFW_UNI_STICK_VERSION = 100a
(7bdc817)
hat es bei mir korrekt gebaut und die configs aus ../etc/skel sind alle da
- schau mal bitte nach ob "./config/includes.chroot/home/user" noch bei dir mit root Rechten existiert.
- wenn ja home/user unbedingt löschen - siehe (https://github.com/fsfw-dresden/usb-live-linux/issues/64#issuecomment-257445585) 
- ansonsten hab ich dafür keine Erklärung.  ./build.log ?

**Comment by Nos-** [comment]
Nun funktioniert es.

**Comment by gerdg-dd** [comment]
Ist hier noch was zu erledigen ? 
Ich wäre für schließen.

**Comment by cknoll** [comment]
Tex-Studio-Verknüpfung fehlt und Anordnung könnte logischer sein
