### ISSUE TITLE
FSFW_-_USB-Stick_erstellen - UEFI unterstützung einbauen

### ISSUE THREAD

**Issue by gerdg-dd** [fsfw-dresden/usb-live-linux#122]
[FSFW_-_USB-Stick_erstellen](https://github.com/fsfw-dresden/usb-live-linux/blob/develop/tools/FSFW_-_USB-Stick_erstellen.sh)

- [ ]  anpassen des Partitionierens -  gdisk / sgdisk verwenden (Bios-GPT und UEFI-GPT) sollen funktionieren
 partition layout erstellen z.B.: 

`sgdisk --clear \`
`--new 1::+1M --typecode=1:ef02 --change-name=1:'BIOS boot partition' \ `
`--new 2::+100M --typecode=2:ef00 --change-name=2:'EFI System' \ `
`--new 3::-0 ................................   \ `
`FSFW-USB-Stick.img `

- [ ] grub installieren anpassen - module ext2 part_gpt müssen dabei sein
- [ ] EFI boot image erstellen
- [ ] grub.cfg anpassen

**Comment by eMPee584** [comment]
Ok das ist wichtig; hatte es erfolgreich verdrängt (mein ADHS-Hirn hat zwischendurch so blinde Flecken).. dachte unterbewusst, dafür ist doch dieses `tools/FSFW_-_USB-Stick_erstellen.sh` entstanden überhaupt. Hab gar nicht allumfassend realisiert dass ich den maintainer-Hut gerade auf habe..
Naja iteratives Vorgehen^^

**Comment by eMPee584** [comment]
Also, habe es geschafft, grub & efi-files zu kombinieren so dass der ausgelieferte Stick sich nachrüsten lässt; kommt bald ins repo. Ein paar Platzhalter für mich noch:
https://wiki.ubuntuusers.de/EFI_Nachbearbeitung/#Secure-Boot-nachruesten
https://wiki.ubuntuusers.de/EFI_Externer-Datentr%C3%A4ger/#Anpassen-GRUB-Basis
https://wiki.archlinux.org/index.php/Multiboot_USB_drive

**Comment by eMPee584** [comment]
fixed with 568331512d28b848fd2013380034def5fa078e78
