### ISSUE TITLE
Fehlende Pakete (2018-branch)

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#123]
Beim Versuch den Branch  2018 zu bauen, erhielt ich die Fehlermeldung das folgende Pakete nicht gefunden werden konnten:

* nextcloud-client-dolphin
* nextcloud-client-nautilus

Ich konnte sie weder in der Debian-Paketsuche noch in einer unserer Softwarelisten finden, was für eine fehlerhafte Abhängigkeit in einem der Pakete spricht.

**Comment by eMPee584** [comment]
nein das spricht dafür dass ich vergessen habe das nextcloud repo zu committen..
