### ISSUE TITLE
Thunderbird vs. Icedove

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#130]
Hallo,

soweit ich weiß macht Thunderbird das Rennen. In [paketlisten/kommunikation.md](https://github.com/fsfw-dresden/usb-live-linux/raw/2018/variants/FSFW-Uni-Stick_KDE_stretch_amd64/paketlisten/kommunikation.md) steht jedoch noch Icedove drin. 
Soll das so oder sollte das mal geändert werden?

**Comment by eMPee584** [comment]
paketnamen firefox, thunderbird sind erst wieder in unstable.
in aktivierten stable-backports sind aktuelle, gepflegte Versionen drin.
