### ISSUE TITLE
sweethome3d sinnlos ohne Möbel?

### ISSUE THREAD

**Issue by eMPee584** [fsfw-dresden/usb-live-linux#131]
93M sweethome3d-furniture
44M sweethome3d-furniture-nonfree

Schlage vor, entweder das Programm zu de- oder beide Objektpakete zu aktivieren.

```
/usr/share/doc/sweethome3d-furniture-nonfree/copyright
License: Free-Art-1.3
 2.2 FREEDOM TO SPREAD (TO INTERPRET, TO REPRESENT, DISTRIBUTE)
```

**Comment by Nos-** [comment]
Hm, wenigstens `sweethome3d-furniture` fände ich (für die nächste Ausgabe) gut.

**Comment by eMPee584** [comment]
Die Paketquellen sind aktiviert worden, müssen nur noch einsortiert werden..
