### ISSUE TITLE
Imagetest (Branch: 2018, Version 815c bzw. Commit 576264)

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#135]
Der Loginscreen sieht zwar schick aus (obwohl es vorher auch nicht schlecht war) aber wie kann ich mich da nun einlogen?

![screenshot_unistickdebian9_2018-10-17_08 37 30](https://user-images.githubusercontent.com/6155874/47067004-2b11ba00-d1e8-11e8-8a43-fcd6182a756f.png)

Da ich eigentlich die XFCE-Variante testen wollte baute ich das Image mit:
`scripts/build-live-system.sh FSFW-Uni-Stick_Xfce_stretch_amd64`

**Comment by eMPee584** [comment]
> > Da ich eigentlich die XFCE-Variante testen wollte baute ich das Image mit:
> > |scripts/build-live-system.sh FSFW-Uni-Stick_Xfce_stretch_amd64|

mutig 😄
das geht so nicht, das ist nur ein minimaler Stumpf.. xfce nutzt lightdm statt sddm, sieht so aus als sei beides drin gelandet (weil auf dem screenshot ist KDEs sddm IIRC)..
