### ISSUE TITLE
Softwareliste M18 zum vergleich

### ISSUE THREAD

**Issue by vv01f** [fsfw-dresden/usb-live-linux#138]
s. https://m18.uni-weimar.de/service/software

**Comment by Nos-** [comment]
Hmm, da ist einiges dabei, das ich mal ausprobieren müsste

**Comment by Nos-** [comment]
Aber erstmal ist [Open-Modellica](https://openmodelica.org/) dran mit ausprobieren. Kennt sich jemand mit Maschbau oder Simulation aus?

**Comment by eMPee584** [comment]
(es gibt viele Example-Files u man kann durch die Modelle auf die untersten physikalischen Ebenen durchklicken... schon sehr geil)
(Das +AI = :rainbow: :gear: )

**Comment by eMPee584** [comment]
k sumatrapdf könnte ich vielleicht noch reinziehen, sonst haben wir das eigentlich auch alles an Board..
