### ISSUE TITLE
gnupg missing Error beim Imagebauen

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#145]
Testsystem ist ein virtualisiertes Debian 9.9.
![Screenshot_debian9_2019-05-17_19:22:33](https://user-images.githubusercontent.com/6155874/57951021-44e3be80-78e9-11e9-8930-dd4553880a56.png)
Übrigens: das als fehlend beklagte gnupg ist installiert und zusätzlich der Systemtools-Liste hinzugefügt.

_Originally posted by @Nos- in https://github.com/fsfw-dresden/usb-live-linux/pull/144#issuecomment-493570223_

**Comment by Nos-** [comment]
> > Allerdings baut es bei mir leider nicht.
> > Testsystem ist ein virtualisiertes Debian 9.9.
> > Übrigens: das als fehlend beklagte gnupg ist installiert
> 
> in der VM? `dpkg -s gnupg|grep Status`
> 
Status: install ok installed

> > und zusätzlich der Systemtools-Liste hinzugefügt.
> 
> na das bringt ja vermutlich bei dem Fehler kaum was wa.

Naja, ich wollte es nicht unversucht lassen.

> Und der Teil des Logs vor dem Fehler kommt öfter, interessant ist was davor kommt. Also wenn du das komplette Log posten könntest...

Kommt gleich.

**Comment by eMPee584** [comment]
…was zur H*lle? :open_mouth: 
Logfiles doch nicht ins git pushen :rofl:

:floppy_disk: [build_Issue#145-gnupg-missing-error.log](https://github.com/fsfw-dresden/usb-live-linux/files/3211951/build_Issue.145-gnupg-missing-error.log)

**Comment by eMPee584** [comment]
Also. Du hast eine debian-stable VM genommen. Dort ist ein uraltes live-build (20170213) drin. Dieses benutzt noch apt-key um die keys hinzuzufügen, und das wiederum benötigt ein volles `gpg`, nichts das Mini-`gpgv` das im bootstrap installiert wird.. siehe changelog

```
 live-build (1:20180618) unstable; urgency=medium
 
   * ONIE: make lb clean remove the ONIE binary.
   * Avoid apt-key add and just drop the custom user-supplied apt key in
     /etc/apt/trusted.gpg.d. Note that this requires the key to be in
     armored ASCII format - which is usually the default anyway.
```

Entweder du updatest live-build auf das aus dem unstable, oder .. 
ok fix committed, please test.

**Comment by Nos-** [comment]
Es baut und startet. Danke.

**Comment by eMPee584** [comment]
na wurd auch Zeit dass es mal wieder baut :sweat_smile:

**Comment by eMPee584** [comment]
wie lang hat es dafür gebraucht btw?

**Comment by Nos-** [comment]
> wie lang hat es dafür gebraucht btw?

Die aktuelle Version hat ca. 2h zum Bauen des Images gebraucht.
