### ISSUE TITLE
Doku im Webbrowser kann nicht gefunden werden

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#146]
Nach dem Booten wird automatisch ein Webbrowser geöffnet, der eigentlich eine (lokale) Doku anzeigen soll. Diese scheint aber zu fehlen, denn andere Webseiten gehen.

Vermutlich habe ich einfach einen Schritt beim Bauen des Images für den Stick ausgelassen. Falls dem so ist, wäre eine entsprechende Ergänzung der Anleitung gut.

**Comment by eMPee584** [comment]
nein du hast dein repo nicht gesynct
ich habe ein funzendes image mit don't worry
hab nix mehr geändert seit gestern



-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Nos-** [comment]
Leider funzt es auch mit einem neu gebauten Image ( 2019-07-07_FSFW-Uni-Stick_1074o_Xfce_buster-amd64.hybrid.iso ) bei mir nicht.
Ich habe zusätzlich die Daten der Win-Partition mit drauf kopiert, nachdem ich den Usb-Stick komplett neu partitionieren lassen habe. Gern stelle ich das Logfile zur Verfügung.

**Comment by eMPee584** [comment]
verstehe ich nicht so wirklich..
... also ganz sicher kein altes Persistenz-volume?
erstelle doch mal eine Image-Datei, z.B. mit `IMG="/mnt/x/fsfw-$(date +%F).img"; fallocate -l 6G "${IMG}"`, dann als loop-device einrichten `losetup -vPf "${IMG}"` und mit `losetup` schauen welches device .. dann mit dem stick-install-skript einrichten.

**Comment by gerdg-dd** [comment]
aktuell gebautes Image aus dem master  ergiebt
4413136896 Okt  8 21:26 Dresden-Grundschulstick_1171t_Xfce_buster-amd64.hybrid.iso
zeigt keine doku im Browser  an
- /usr/local/share/doc/FSFW-Dresden gibt es zwar, aber keine stick-doku/index.html
