### ISSUE TITLE
stick-install.sh - parted nor found error

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#150]
scripts/stick-install.sh bricht ab mit Fehlermeldung das `parted`nicht gefunden werden konnte. Tatsächlich ist es aber installiert (allerdings nur als root nutzbar).

Lösung: Script als root/ per sudo ausführen. Das hat den Vorteil das auch weitere Berechtigungsprobleme (z.B.: mounten) gelöst werden.

**Comment by gerdg-dd** [comment]
siehe Zeile 4 im script
#        USAGE: sudo scripts/stick-install.sh /dev/sd...  ( Gerät/USB-Stick der benutzt werden soll )
