### ISSUE TITLE
Alternative zu live-build erproben

### ISSUE THREAD

**Issue by eMPee584** [fsfw-dresden/usb-live-linux#155]
Der momentane Build-Prozess und der resultierende Aufbau des Repos beschränkt stark die Modularität und Flexibilität, die man für die Erstellung von unterschiedlichen Varianten benötigt.
Deswegen ist ein mittelfristiger Umzug zu einem anderen Werkzeug angezeigt.

Insbesondere Dich @gerdg-dd würde ich bitten, dies voranzutreiben :cowboy_hat_face:

**Comment by gerdg-dd** [comment]
Umzug zu einem anderen Werkzeug 
funktionale Vorschläge ? - die möglichst auch funktionieren

**Comment by eMPee584** [comment]
Sorry dass ich noch nicht gemeldet habe, sterbefall..
habe einiges mir angeschaut und vmdb2 scheint vorerst das tool der wahl..
ich überlege die ganze zeit, wie man am besten einzelne featurekombis aus paket und settings entkoppelt von den varianten und optional organisieren kann..

**Comment by Nos-** [comment]
Ich probiere gerade Nix, könnte mir aber vorstellen, das auch Ansible hilfreich sein könnte.

**Comment by eMPee584** [comment]
.. erst mal kein Thema, `live-build` wird wieder maintained, funktioniert stabil und ein Wechsel wird dann wieder mal einen mittelgroßen Umbau benötigen. Wenn es soweit ist 😅
