### ISSUE TITLE
Blender 2.8 Installation

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#156]
Auf dem Stick aus dem Frühjahr 2020 ist nur die Version 2.79b statt die deutlich modernere Version 2.8 installiert.

Grund: in den [Debian-Repos](https://packages.debian.org/search?keywords=Blender&searchon=names&suite=stable&section=all) gibts nur die alte Version.

Abhilfe: [Blender 2.8](https://www.blender.org/download/) für Debian paketieren oder eine Installationskurzanleitung in der Doku ergänzen. (Die Software ist nach dem Entpacken sofort nutzbar)

**Comment by eMPee584** [comment]
dabda49e3d10623575b2470dec9da0cfddba7fec
