### ISSUE TITLE
Add info about testing Schulstick linux at distrotest to README.md

### ISSUE THREAD

**Issue by freddii** [fsfw-dresden/usb-live-linux#160]
It is possible to test Schulstick Linux at:

https://distrotest.net/Schulstick%20Linux/2020.0

That might be useful info that could be added to README.md, so nobody has to download 7 GiB just to test it.

**Comment by cknoll** [comment]
Big thanks for your contribution!
I pinged the stick-experts on our mailing list to make sure this doe not get lost.

**Comment by eMPee584** [comment]
Of course this wouldn't get lost 😅
Obviously, this is a very nice feat, THANKS @freddii!
We are just putting finishing touches on the first round of releases for this year; there have been 200 commits since 2020.0 .. few more pending.

**Comment by freddii** [comment]
The new demo link is: 
https://distrotest.net/Schulstick%20Linux/2021.4

updated the demo and download links in pull request #166
