### ISSUE TITLE
Eine weitere Einsteiger-GUI für die Python-Entwicklung

### ISSUE THREAD

**Issue by NSchwirz** [fsfw-dresden/usb-live-linux#169]
Kennt jemand PySimpleGUI und kann Erfahrungswerte beisteuern?

Hier der Link: https://github.com/PySimpleGUI

**Comment by cknoll** [comment]
Das ist aus meiner Sicht keine GUI für die Entwicklung (wie Spyder oder PyCharm) sondern ein Framework, um in Python GUI-Programme zu schreiben. Ich sehe die Relevanz für den Stick aktuell nicht. (Weniger Kram zugunsten von mehr Übersicht.)

**Comment by Nos-** [comment]
Ok, danke für die Richtigstellung.
