### ISSUE TITLE
Berechtigungsproblem, einen beim mounten

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#17]
Ich habe beim Ausprobieren und Anpassen des Live-Systems (aktueller Stand des Branches ck/aktuelles_python) gerade festgestellt, dass eine Fehlermeldung kommt, wenn ich aus Dolphin (KDE-Dateimanager) heraus einen zusätzlichen USB-Stick oder eine interne Platte mounten will. Auf meiner Debian Jessi-Installation ging das aber von Anfang an.

der Benutzer `user` ist in der Gruppe `plugdev` drin.

Kann das Problem jemand bestätigen? oder Wichtiger: lösen?

**Comment by cknoll** [comment]
@gerdg-dd  @Nos- Könnt ihr das Problem bestätigen?

**Comment by gerdg-dd** [comment]
getestet mit USB-Stick vom Plenum - funktioniert das 

- könnte es sein, das der Grund die .bashrc,  die du dem user unterschiebst, ist

für Änderungen an der bashrc 
 - nimm am besten die Basis aus dem erstellten Livesystem  ../FSFW-Uni-Stick/chroot/etc/skel/.bashrc  
- Änderungen über hook einfügen
- alternativ über hook oder per Hand und einfügen in
../FSFW-Uni-Stick/config/includes.chroot/etc/skel/.bashrc 
oder
../FSFW-Uni-Stick/config/includes.binary/etc/skel/.bashrc

**Comment by gerdg-dd** [comment]
Notlösung :

Stick vom Master erstellen (sollte funktionieren)
  - Anpassungen direkt auf dem Stick vornehmen 
  ( Aktuelles Jupyter/IPython installieren, Symbole auf dem Desktop anzeigen, Windows Programme kopieren auf Partition WIN-DATEN) 
  - Image kopieren / sichern 
  - Änderungen später im Masterbranch ergänzen

**Comment by cknoll** [comment]
Danke für den Tipp mit der .bashrc.

Bin dran und sieht nicht schlecht aus.

**Comment by cknoll** [comment]
Trat nicht wieder auf..
