### ISSUE TITLE
Build-error

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#170]
Beim Versuch den "Basisstick:Xfce:bullseye" zu bauen erhielt ich gerade die folgende Fehlermeldung:

> $ sudo scripts/build-live-iso "Basisstick:Xfce:bullseye"
...
> Reading package lists...
> W: GPG error: http://deb.anydesk.com all InRelease: The following signatures were invalid: EXPKEYSIG 18DF3741CDFFDE29 philandro Software GmbH <info@philandro.com>
> E: The repository 'http://deb.anydesk.com all InRelease' is not signed.
> E: An unexpected failure occurred, exiting...
> P: Begin unmounting filesystems...
> P: Saving caches...
> Reading package lists...
> Building dependency tree...
> [ 🛑 ] FAILED
> [ ℹ️  ] this took 3 minutes and 50 seconds and the work of many

Wie es aussieht ist ein Schlüssel abgelaufen.

**Comment by Nos-** [comment]
Ohne Anydesk funktioniert es.

**Comment by eMPee584** [comment]
Ja, hatte die schon angetwittert, ist gestern abgelaufen..
du könntest den Feature-Symlink auch umbennenen in `app_anydesk_remote_support.disabled`, damit wird es auch deaktiviert..
Temporärer, lokaler Workaround um solche 🗝-Fehler zu ignorieren ist, in der entsprechenden `sources.list` zwischen dem `deb` und der URL `[trusted=yes]` einzufügen, siehe [features/app_qucs-s_electronics_simulation/package-repos/qucs-s.list](https://github.com/fsfw-dresden/usb-live-linux/blob/master/features/app_qucs-s_electronics_simulation/package-repos/qucs-s.list) .. wirklich schön (und sicher) ist das natürlich nicht, deswegen warte ich auf einen geupdateten Key von philandro..

**Comment by Nos-** [comment]
Danke für die schnelle Antwort. Gute Arbeit soweit.

**Comment by Nos-** [comment]
Hm, wie es scheint reicht es leider nicht anydesk aus der Paket(wunsch)liste zu nehmen. Aufgrund des abgelaufenen GPG-Keys des Repos muss das ganze Repo wenigstens auskommentiert werden.

**Comment by eMPee584** [comment]
mich dünkt: jemand hat sein repo nicht erfrischt 🙃

----------------------------------------

*From: *Nos- ***@***.***>
*To: *fsfw-dresden/usb-live-linux ***@***.***>
*CC: *Marcel Partap ***@***.***>; Comment ***@***.***>
*Date: *9 Jan 2022 12:42:49
*Subject: *Re: [fsfw-dresden/usb-live-linux] Build-error (Issue #170)

**Comment by Nos-** [comment]
Leider trat der Fehler erst vor ein paar Tagen wieder auf. Ein Entfernen des Features (Anydesk) samt Repo half.

**Comment by eMPee584** [comment]
Es steht mittlerweile ein `[trusted=yes]` in der `anydesk.list`, deswegen ist es von Fehler (`E:`) auf Warnung (`W:`) herabgestuft, breakt also nicht mehr den Build..
Muss mal in Berlin anrufen und um ein Key-Update betteln, twittern hat wohl nicht gereicht 😄
