### ISSUE TITLE
Buildproblem due to new github-security

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#178]
It seems that github deprecated some insecure protocols:

```
[...]

Cloning into 'spacehi.vim'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
E: config/hooks/normal/0540-vim-plugins.hook.chroot failed (exit non-zero). You should check for errors.
E: An unexpected failure occurred, exiting...

[...]
```

**Comment by eMPee584** [comment]
Ah danke cool .. . 🥳
ich schlage mich gerad noch mit zwei anderen Release-Blockern rum, nämlich dass der `xfce4-power-manager` statt Standby meckert und die Konfiguration des Desktop-Hintergrundes kaputt ist.. hoffe, das heute noch hinzubekommen .. #nichttrivial
