### ISSUE TITLE
Need to use English as the standard language 

### ISSUE THREAD

**Issue by DutKulang** [fsfw-dresden/usb-live-linux#183]
``` this repo is gaining international attention it will be helpful if English is to considered the main language used for development, we would like contribute but the need translate everything bores us. ```
@DutKulang from South Sudan

**Comment by eMPee584** [comment]
Yes of course Dut you are right, most of the project is in english already however, just few pieces of information and the default setting is german.. now the [german homepage](https://schulstick.org/) is ready and focus is on a german release first.. we will be publishing updated images soon. You can start the existent image with boot option `locales=` to make the system not set language to german.
