### ISSUE TITLE
Test Portal on Schulstick

### ISSUE THREAD

**Issue by DerDennisOP** [fsfw-dresden/usb-live-linux#190]
Make the Portal available on the Schulstick and test main features.

Dependency of https://github.com/fsfw-dresden/schulstick-tutorial-docs/issues/1

**Comment by eMPee584** [comment]
Working with these files:
https://github.com/fsfw-dresden/LiaScript-DevServer/releases/download/1.1.31-fsfw-2/liascript-devserver_1.1.31_all.deb ()
https://github.com/fsfw-dresden/learning-portal/releases/download/v0.1.3b/schulstick_0.1.3_all.deb
