### ISSUE TITLE
gimp-ufraw vs. darktable

### ISSUE THREAD

**Issue by horazont** [fsfw-dresden/usb-live-linux#2]
Ich würde, wenn wir ``gimp-ufraw`` drin haben wollen, eher für ``darktable`` stimmen – für das Zielpublikum von ``gimp-ufraw`` ist ``darktable`` das bessere tool.

**Comment by gerdg-dd** [comment]
` darktable ` - zur Paketliste hinzugefügt -- testen

` rawtherapee ` -  Freier RAW-Umwandler und Fotobearbeitungssoftware  
" Ist für mich das  bessere Toot "

**Comment by Nos-** [comment]
Hmm, habe wegen Digikam gerade eine Version mit _dcraw_ (statt _ufraw_) und _rawtherapee _ gebaut. Falls gewünscht, kann das aber auch nochmal anders probieren.
