### ISSUE TITLE
Test und Doku: TeXstudio auf Windows

### ISSUE THREAD

**Issue by vv01f** [fsfw-dresden/usb-live-linux#20]
Die Installationsgröße sieht für CK verdächtig klein aus; es besteht Sorge, dass unsere eigene Vorlage nicht bauen wird.
- [x] Test und Ergebnis vermerken – Schriftart wurde auskommentiert (aktuell Zeile 44 in Vorlage für Diplomarbeit) um erfolgreich zu bauen
- [ ] Dokumentation eventuell notwendiger Schritte von dem initialen Paket von PortableApps.com aus.
  - Paket entpacken
  - Konfiguration aufrufen
  - Pfade zu den einzelnen Binaries innerhalb der ProtableApp heraussuchen
  - Laufwerkbuchstaben durch relativen Pfad ersetzen – ungeklärt, ob es (wie bei Firefox) auch ohne geht

**Comment by vv01f** [comment]
Anleitung für die Konfiguration für ein portables LaTeX für Windows kann u.a. auf

* [Configuring portable TeXstudio to use MiKTeX
portable](http://tex.stackexchange.com/questions/42940/ddg#53484)
* [es gibt texlive portable für
Windows](http://disrerihouns.ampblogs.com/texlive-portable-windows-download-1422090)

basieren.

**Comment by vv01f** [comment]
* configs für binaries funktionieren, "einfach" Lw-Buchstaben durch ".." ersetzt; nicht vorhandene auf "&lt;unbekannt&gt;".
* vorlage baut nicht – beramono (aus fotns-extra)
* [ ] => auskommentieren

**Comment by cknoll** [comment]
Wie ist hier der Stand?

**Comment by cknoll** [comment]
@Nos- probiert den aktuellen Windowsstand mal an einem Rechner in der Slub

**Comment by Nos-** [comment]
Es funktioniert immer noch nicht. Sobald die Zeile mit der Einbindung der Beramono-Font einkommentiert wird gibts ein Problem.

Am 26. Oktober 2016 21:12:41 MESZ, schrieb "C. Knoll" <notifications@github.com>:
>@Nos- probiert den aktuellen Windowsstand mal an einem Rechner in der
>Slub
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/fsfw-dresden/usb-live-linux/issues/20#issuecomment-256448277

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by s72785** [comment]
@Nos- meint, es funktioniert einwandfrei, wie gedacht; Schriftart (aus fonts-extra) muss aber auskommentiert sein.

**Comment by Nos-** [comment]
Jo, so siehts aus.

**Comment by cknoll** [comment]
D.h. hier besteht vorerst kein Handlungsbedarf. Issue kann geschlossen werden (?)

**Comment by s72785** [comment]
Kein dringender jedenfalls.
Wenn die Schriftart wichtig genug wäre, könnte man in einem Kommentar auf eine Anleitung zur Nachinstallation verweisen um das Issue zu behandeln.

**Comment by cknoll** [comment]
Ob die Schriftart beramono wichtig ist, müsste @exot entscheiden (Vorlage ist ja von ihm). Falls nicht kann er dieses Issue dann auch gleich schließen.

**Comment by exot** [comment]
Ist nicht wichtig.
