### ISSUE TITLE
müsste man mal: torrent für image

### ISSUE THREAD

**Issue by vv01f** [fsfw-dresden/usb-live-linux#22]
sobald das image irgendwo liegt, ist das Erstellen eines Torrents gefragt.

* [x] torrent-Datei (geht in den meisten Clients, bsp: uTorrent, Trnasmission, Deluge) erstellen
* [x] erstellte Datei in Magnet-Link übertragen (unterstützt kaum ein Client vollständig, insb. Webseed)
* [x] in Doku verlinken

Magnet sieht aus:

```
    "magnet:?xt=urn:btih:"${torrent-hash}"&dn="${filename}"&tr="${tracker-uri}"&ws="${webseed-href-of-file}"&as="${href-of-torrent-file}
```

Dabei dürfen es auch mehrere Tracker sein.

**Comment by vv01f** [comment]
done

**Comment by s72785** [comment]
torrent updated, 2nd websee; thx @horazont

**Comment by s72785** [comment]
magnet worx with transmission-cli - yeah \o/
