### ISSUE TITLE
Persistenz vergößern

### ISSUE THREAD

**Issue by s72785** [fsfw-dresden/usb-live-linux#35]
- [ ] Doppelungen bei Programmen erkennen und möglichst beseitigen
- [x] Identifizieren von Platz-Fressern, Kriterium &gt; x MB ?
- [x] Anleitung so gestalten, dass Interessierte z.B. einen 16 GB Stick sauber bespielen und nutzbar machen können.

Weitere Ideen? :)

**Comment by Nos-** [comment]
Ein `cat paketliste* | sort | uniq -c | sort -n` sollte die Anzahl aller Pakete als sortierte Liste ausgeben. Einträge ohne "1" in der ersten Spalte sind folglich mehrfach.
`cat paketliste* | sort | uniq` liefert folglich eine Liste ohne Dubletten und Anzahl.

**Comment by s72785** [comment]
schritt 2 mit #45 getan

**Comment by Nos-** [comment]
Habe gerade die Persistenz mit dem vorhin neugebauten Stick probiert und es funktionniert. (Lag wohl wirklich an der größe der Persistenzpartition)

**Comment by gerdg-dd** [comment]
ich würde das hier schließen, da Persistence prinzipiell funktioniert
- beachte https://github.com/fsfw-dresden/usb-live-linux/issues/46

**Comment by cknoll** [comment]
sehe ich auch so
