### ISSUE TITLE
kile?

### ISSUE THREAD

**Issue by horazont** [fsfw-dresden/usb-live-linux#4]
Da TeXlive dabei ist, kile als KDE-integrierten LaTeX-Editor?

**Comment by exot** [comment]
Lieber TeXstudio, denn das läuft auch unter anderen Oberflächen und auch anderen Betriebssystemen.

**Comment by Nos-** [comment]
Naja, ich habe sie bei mir erstmal testhalber beide hinzugefügt.

**Comment by vv01f** [comment]
TeXStudio gibt für mehr Plattformen => würde ich präferieren; aber man kann auf die Alternative hinweisen wenn Sie z.B. komfortabler sein sollte (Argumente sind wichtig)

**Comment by Nos-** [comment]
Naja, ist einer der Kile-Hauptentwickler hier an der TU? (Ich bin dafür beides zu installieren und von mir aus TeXstudio als primäres Tool zu verlinken.)

**Comment by s72785** [comment]
Dann diesen Umstand hervorheben und Links setzen; ggf. Anleitung zum Wechsel in eine andere TeX-Umgebung.

**Comment by cknoll** [comment]
wer macht das?

**Comment by Nos-** [comment]
Wie ist hier der Stand?

**Comment by cknoll** [comment]
Ist derzeit nicht so relevant.
