### ISSUE TITLE
Paketliste überarbeiten

### ISSUE THREAD

**Issue by gerdg-dd** [fsfw-dresden/usb-live-linux#45]
FSFW-Uni-Stick/auto/config
--apt-recommends false \
- hab diese Option eingefügt, da sie verhindert das Empfohlene Pakete automatisch installiert werden
  z.B texlive-latex-extra-doc ... 
- einige Pakete hab ich schon nachgetragen damit das Image auch baut und prinzipiell funktionsfähig ist.
- aktuelle Größe nach dem bauen ca. 2,4 GB
  2401763328 Okt 18 18:21 FSFW-Uni-Stick_jessie-amd64.hybrid.iso
- es kann sein das noch Pakete fehlen die gebraut werden  !
- bitte testen 
- dif FSFW-Uni-Stick/FSFW-Uni-Stick_jessie-amd64.packages mit Liste vom Stick /live/filesystem.packages
- Pakete die bisher automatisch Installiert wurden und jetzt fehlen müssen nachgetragen werden
- melden oder selber eintragen

**Comment by cknoll** [comment]
@gerdg-dd: Diese Option ist sehr gut.

Vorschlag zum weiteren Vorgehen:
@Nos-  könntest Du mal aus dem bisherigen Image die **komplette** Liste aller Pakete rausziehen. Muss irgendwie mit apt/dpkg gehen. Am besten den Befehl gleich noch hier ins Issue schreiben. Wenn @gerdg-dd das gleiche mit dem neuen Image macht (er hat es ja schon gebaut, sollte also nicht viel Aufwand sein) dann kann man hoffentlich im Diff die Unterschiede sehen.

**Comment by gerdg-dd** [comment]
Die komplette Liste aller installierten Pakete 
- liegt im FSFW-...*.iso Image in der Datei "/live/filesystem.packages"
- im live-build Systemverzeichnis in der Datei "FSFW-Uni-Stick/FSFW-Uni-Stick_jessie-amd64.packages"

- bitte testen:  
  - bezieht sich auf alle die ein neues Image bauen und auf Funktionalität überprüfen 
  - falls Probleme auftreten --> Listen vergleichen
- @cknoll +1  ein automatisierter Testlauf wäre super - Wer übernimmt das ? Freiwillige ?

**Comment by gerdg-dd** [comment]
[2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt](https://github.com/fsfw-dresden/usb-live-linux/files/538286/2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt)

**Comment by Nos-** [comment]
Hmm, mit `apt-mark showmanual` kann man sich alle manuell ausgewählten und mit `apt-mark showauto` alle automatisch nachgezogenen Softwarepaket anzeigen lassen.

Siehe auch: [/doc/WeiterePaketevorschlaege.md#wie-diese-liste-erstellt-wurde](https://github.com/fsfw-dresden/usb-live-linux/blob/master/doc/WeiterePaketevorschlaege.md#wie-diese-liste-erstellt-wurde)

**Comment by cknoll** [comment]
@gerdg-dd Ist die Datei [2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt](https://github.com/fsfw-dresden/usb-live-linux/files/538286/2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt) jetzt gerade die Differenz zwischen den beiden Build-Läufen?

Pragmatischer Vorschlag: wir sollten versuchen für die Liste automatisiert rauszufinden wie groß jedes Paket ist. Und nur die großen Fische (>20 MB) weglassen. Immerhin sind sie ja empfohlen und das wird schon seinen Grund haben.

Den Rest würde ich über eine separate Liste mit in den Build einbeziehen. Das erspart uns ggf. subtile Probleme, wie z.B. dass auf manchen Plattformen X.org nicht geht oder so...

@Nos- Die Listen sind zwar nett, aber ich habe noch nicht verstanden wofür wir die brauchen. Wir brauchen ja die "Differenz" der **kompletten** Pakatlisten. Mir ist unklar, ob die Vereinigung der beiden Listen (manuell und auto) die Komplette Liste ergibt. Außerdem müsste man diese dann noch sortieren, dass man sinnvoll diff anwenden kann.

**Comment by gerdg-dd** [comment]
ja [2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt](https://github.com/fsfw-dresden/usb-live-linux/files/538286/2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt) ist die diff
der Paketliste vom verteilten Stick-Image zum aktuellen master branch

**Comment by cknoll** [comment]
@Nos- Weißt Du zufällig, wie man aus [Gerds Liste](https://github.com/fsfw-dresden/usb-live-linux/files/538286/2016-10-19_-_nicht_mehr_automatisch_installierte_Pakete.txt) für jedes Paket rausbekommt wie groß es (ohne Abhängigkeiten) ist? Dann könnten wir nämlich einfach der Größe nach sortieren...

**Comment by gerdg-dd** [comment]
z. B.
$ dpkg -p texlive-latex-extra-doc | grep Installed-Size
Installed-Size: 447204

**Comment by Nos-** [comment]
Hey danke Gerd für die Antwort. Ich komme erst ab morgen wieder dazu mich hierum zu kümmern und habe selbst auch noch 2 Programme, die ich gern mit dabei hätte.

**Comment by Nos-** [comment]
Mir fallen auf die Schnelle Folgende Ansätze zur Größenermittlung der ausgewählten Softwarepakete ein:

* Gerds Skript in einer Schleife für alle Pakete in der Datei
* mit *libapt* für python versuchen etwas zu stricken (Wer kann Python programmieren?)
* mit `apt-get --dry-run` rumprobieren

Speziell die letzte Variante hätte den Vorteil, das man ohne großen (Rechen-, Download- und Zeit-)aufwand eine Liste potenzieller Fehler angezeigt bekommt. Also z.B. einfach in einer chroot-Umgebung erstmal `apt-get --dry-run <Paketliste>` ausführen, Gesamtspeicherbedarf und Fehler durchlesen, bevor man es wirklich baut.

**Comment by Nos-** [comment]
So, `auto/paketliste` fragt nun `apt-cache` für jedes Paket:
* wie viel Platz es denn nach der Installation benötigen würde
* und nach dessen Kurzbeschreibung

Einziger Wehmutstropfen: Das Skript sollte auf einem Debian stable mit ähnlicher Apt-Konfig ausgeführt werden (vor allem die gleichen Repos eingerichtet haben). Verbesserungsidee: Apt-cache Abfragen optional machen (etwas per Aufrufparameter).

**Comment by Nos-** [comment]
Paketcheck & -infofnuktion in Extrascript auslagern und im tools-Verzeichnis abspeichern. Namensvorschlag: SoftwareauswahlCheckAndInfo.sh

**Comment by gerdg-dd** [comment]
war für FSFW-Uni-Stick_KDE_jessie_amd64 - ist überholt = erledigt
