### ISSUE TITLE
Systemvoraussetzungen des FSFW-Uni-Stick_kde_jessie-amd64.hybrid.iso vom 16.10.2016

### ISSUE THREAD

**Issue by gerdg-dd** [fsfw-dresden/usb-live-linux#46]
Prozessor: CPU 64 bit 
Speicher:  1 GB RAM  - KDE läuft - Demo im TexStudio erstellen - zu wenig Speicher ?
- kann das jemand bestätigen ?
- bei 2GB RAM funktioniert es
- Persistence-Partition möglichst nicht kleiner 500MB 

Vorschlag: beim 8GB Stick sollte die WIN-DATEN Partition bei ca. max 3 GB Größe liegen
--> Programmauswahl ! - andere nur Verlinken

**Comment by Nos-** [comment]
Hmm, in meiner Virtualbox läuft es mit 2 GB problemlos.

**Comment by gerdg-dd** [comment]
ist für jessie überholt --> siehe stretch (Systemvoraussetzungen des FSFW-Uni-Stick_*_develop__KDE_stretch-amd64.hybrid.iso)
