### ISSUE TITLE
Ersatz für Skype 

### ISSUE THREAD

**Issue by s72785** [fsfw-dresden/usb-live-linux#47]
Skype gibt es auf den mobilen Plattformen genauso wie auf dem Desktop. Viele kennen kaum ein anderes Video-Chat Tool. Welche Freie Software wäre überzeugend genug? Ich habe schon Wire etc. probiert, aber die Verbindung ist dann doch eher nicht zuverlässig, oft auch nur Ton. Und Wenn (wie bei PalavaTV) IPv6 gefordert ist, dann sieht es in DEU/EU noch lange nicht gut aus.

Was kennt ihr?

**Comment by gerdg-dd** [comment]
haben am Sonntag mal "Ring" angetestet - sieht vielversprechend aus, war aber erstmal nur teilweise erfolgreich ( vielleicht auch wegen Zeitmangel )
- ist in debian z.Z erst ab stretch verfügbar 
- über f-droid.org für Android Smartphones

**Comment by Nos-** [comment]
Wie siehts mit [Qabel](https://qabel.de) aus? (Hatte mir heute eine Aufzeichnung eines früheren Talks angesehen, bin aber noch nicht zum Testen gekommen)

**Comment by Nos-** [comment]
Hmm, ich glaube dazu steht auch ein Artikel in der LinuxUser, die ich am LPD-Stand dabei hatte.

**Comment by Nos-** [comment]
in Zeiten des Home-Office ist dies besonders interessant. Daher gibts von Bits&Bäume eine [Vortragsaufzeichnung](https://tube.tchncs.de/videos/watch/6addc421-31f0-4126-be68-fe53e540d6a8) und diverse Blogbeiträge von z.B.: DigitalCourage, FSFE. Meist können sie per Webbrowser ohne Zusatzsoftware genutzt werden. Ansonsten, können ja mal Mumble und Jami getestet werden.

**Comment by eMPee584** [comment]
· qabel zuckt nicht mehr
· also Mumble ist eher minder geeignet weil es keinen maintainten Android-Client gibt..
· **Jami** (previously known as "GNU Ring") ist im Stick, wenn auch rel. alte Version .. was ich noch fixe

**Comment by gerdg-dd** [comment]
Mumble - Client ( noch keine Zeit zum testen)
https://f-droid.org/packages/se.lublin.mumla/

Jitsi Meet - scheint gut zu funktionieren
https://f-droid.org/en/packages/org.jitsi.meet/

Infos zu Android Apps in unserem FSFW-Wiki
http://i7/dokuwiki/doku.php?id=doku:software:programme:android
