### ISSUE TITLE
Fehlende Schriftart für LaTeX-Vorlage

### ISSUE THREAD

**Issue by gerdg-dd** [fsfw-dresden/usb-live-linux#48]
- [ ] Schriftart in Vorlage ändern 

oder
- [ ] bera  Bera fonts (http://mirrors.ctan.org/fonts/bera.zip) ins System integrieren

**Comment by cknoll** [comment]
In der Master-Vorlage ist die Schriftart schon geändert. Das Problem ist, dass die Vorlage an zwei Stellen im Repo liegt. einmal in doc/latex-vorlage und einmal in .../include.chroot/....../FSFW-Material.

Das Prä-Build-Skript auto/paketliste müsste sie von doc nach include.chroot kopieren.

Insgesamt ist das Prä-Build-Phase noch verbesserungsfähig. Siehe auch #51.

**Comment by gerdg-dd** [comment]
in meinem gerade gebauten lmage  funktioniert die Vorlage auch mit 
\usepackage[scaled=0.83]{beramono}

**Comment by cknoll** [comment]
Um diese Aussage richtig einschätzen zu können bräuchte ich mal eine git revision (commit id) auf welcher das gebaute Image basiert. Übrigens damit wir mit den Versionen nicht durcheinanderkommen habe ich in #51 eine m.E.n. gut handhabbare Versionsnummerierung vorgeschlagen. ;-)

**Comment by gerdg-dd** [comment]
ja - commit erfolgt zeitnah, wenn ich die Paketliste ergänzt habe ;-)

**Comment by gerdg-dd** [comment]
im aktuellen master branch gebauten lmage funktioniert die Vorlage auch wieder mit
\usepackage[scaled=0.83]{beramono}

Versionsnummerierung folgt
