### ISSUE TITLE
Image kleiner bekommen

### ISSUE THREAD

**Issue by s72785** [fsfw-dresden/usb-live-linux#49]
Optionen
- [x] komprimieren – ZIP gepackt, um Kompatibilität zu erhöhen
- ✖️  Image Format rumdoktorn
- [x] Durch Pinning die dependencies "recommended" minimieren =&gt; Speichergewinn für User
- [x] Image kleiner bauen als die physikalische Größe (p% zur Vermeidung von "Sektorenfehlern" ermitteln) wie [dokumentiert](https://wiki.fsfw-dresden.de/doku.php/doku/live-system/live-system_testen) – muss vom Distributor beachtet werden

Wenn das ISO einfach als ZIP (ohne rumspielen mit Optionen) gepackt wird, habe ich hier eine Speicherplatzeinsparung von 2 GB. Das spart auch Bandbreite und sehr wahrscheinlich Geduldsfäden bei den Nutzern. Also gerade für den nächsten (hoffentlich dauerhafteren) Release 'ne Idee.

**Comment by s72785** [comment]
ggf. für das build script: [howto shrink](http://softwarebakery.com/shrinking-images-on-linux)

**Comment by s72785** [comment]
mit #45 guten Ansatz gefunden die Paketzahl zu minimieren

**Comment by gerdg-dd** [comment]
Prinzipiell geht das erstellen einer Image-Datei passender Größe auch wie hier beschrieben
https://wiki.fsfw-dresden.de/doku.php/doku/live-system/live-system_testen

- zum bespielen folgendes ausführen
  - im Buildverzeichnis ".../usb-live-linux/FSFW-Uni-Stick"

  `$ sudo ../tools/FSFW_-_USB-Stick_erstellen.sh /dev/nbd0`

WIN-DATEN Partition ist da zwar noch leer, aber wen jemand die Downloadlinks in der 
/doc/src/windows.md passen einträgt lässt sich das mit dem ..FSFW-Uni-Stick/fsfw-uni-stick_build.sh
Skript in der Zukunft automatisieren
Vorschlag: beim 8GB Stick sollte die WIN-DATEN Partition bei ca. 3 GB Größe liegen
--> Programmauswahl ! - andere nur Verlinken

**Comment by Nos-** [comment]
Als Reserve für Speicherfehler des Sticks sollte das Image auf ein virtuelles Device, das etwas kleiner als der Usb-Stick ist, erstellt werden. Es kann anschließend mit dd oder so aufgespielt werden.

**Comment by gerdg-dd** [comment]
- würde ich hier als erledigt betrachten --> schließen ? oder andere Meinungen

**Comment by cknoll** [comment]
sehe ich auch so.
