### ISSUE TITLE
Prä-Build-Konzept und Skript verbessern

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#51]
Vor dem Aufruf von `lb  build` wird bisher `auto/paketliste` ausgeführt. Dieser Name ist aber inzwischen nicht mehr passend, weil da mehr passiert (HTML-Doku aus Markdown bauen und nach include.chroot kopieren.). Zukünftig wird sollte noch mehr passieren:

- [x] Readme.md anpassen
- [x] LaTeX-Doku von doc/.... nach includes.chroot/.... kopieren.
- [x] Externe Pakete an der richtigen Stelle ablegen (z.B. qucs).
- [x]  Aktuelle git-Revision in Datei schreiben (am besten als github-Link), damit man präzise nachvollziehen kann auf welchem repo-Stand das gebootete System basiert. 
- [x] Zusätzlich noch eine einfache Versionsnummer erzeugen. Vorschlag [hier](https://github.com/fsfw-dresden/usb-live-linux/blob/master/tools/calc-version-number.sh). Die Release-Version (siehe entsprechenden git-Tag) wäre demnach 84v und der aktuelle Master 88b. Die Versionsnummer sollte im Dateinamen der Iso-Datei und im Boot-Menü stehen.

Außerdem ist mir noch nicht klar, welche Dateien überhaupt ins repo rein sollen und welche nicht (gebaute HTML-Doku?, anderer Inhalt von FSFW-Material?).

**Comment by Nos-** [comment]
Ich fände es praktisch, wenn die auch gleich im Bootmenü stände (in einer Ecke würde schon reichen)

**Comment by gerdg-dd** [comment]
Alle Datein insbesondere Doku die nicht unmittelbar zum live-build gehören würde ich besser in einen seperaten Bereich haben. Zur Bauzeit kann diese hinzugefügt werden. 
Besser seperates Skript, welches die Aufgabe verdeutlicht, so kann es für Testbauten leicht deaktiviert werden.

**Comment by cknoll** [comment]
@Nos- gute Idee. Beschreibung angepasst.

**Comment by gerdg-dd** [comment]
Versionsnummer / Release-Version  hinzugefügt
https://github.com/fsfw-dresden/usb-live-linux/commit/3958cd3da5a9b5ea55849a42f38a486262ddb0cb

Release-Version fürs Image in - FSFW-Uni-Stick/auto/config
für Release + git-Revision in  tools/fsfw-user_config.sh --> home/user/.version_fsfw-uni-stick

**Comment by Nos-** [comment]
Bitte mal die Doku (für uns/ die Erstellung) anpassen, damit man nicht durcheinander kommt.

**Comment by gerdg-dd** [comment]
sollte erledigt sein https://github.com/fsfw-dresden/usb-live-linux/commit/db26de8dc447f3fdcf2f84870562034d1dfdaa93
