### ISSUE TITLE
Dateityp-Assoziationen

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#52]
- [ ] mp3 mit VLC statt wie aktuell mit audacity

relevant ist folgende Datei (für den Benutzer `user`):

https://github.com/fsfw-dresden/usb-live-linux/blob/master/FSFW-Uni-Stick/config/includes.chroot/home/user/aux-files/home-dir/.local/share/applications/mimeapps.list

**Comment by cknoll** [comment]
Fällt mit ab, wenn KDE-Konfig funzt

**Comment by gerdg-dd** [comment]
funktioniert bei mir 
FSFW-Uni-Stick_96n_jessie-amd64.hybrid.iso

hake ich mal mit https://github.com/fsfw-dresden/usb-live-linux/commit/db26de8dc447f3fdcf2f84870562034d1dfdaa93 ab
