### ISSUE TITLE
root passwort beim image-bauen

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#54]
Ich bin gerade beim Bauen aus dem aktuellen Master an folgendem Problem hängen geblieben:

    Setting up printer-driver-cups-pdf (2.6.1-15) ...
    All runlevel operations denied by policy
    invoke-rc.d: policy-rc.d denied execution of force-reload.
    Password for root on localhost?

`live` als Passwort hat nicht funktioniert.. Jedenfalls ist das sehr kritisch, denn es verhindert das Bauen. @gerdg-dd @Nos- Könnt Ihr das Verhalten bestätigen? Habt ihr eine Idee?

**Comment by cknoll** [comment]
Wenn ich das Paket `printer-driver-cups-pdf`. rausnehme, dann geht es.

**Comment by gerdg-dd** [comment]
Wieso er da ein passwort abfragt ist mir rätselhaft ? Bei mir läuft das so durch.

**Comment by Nos-** [comment]
Hmm, ich lass gerade im Hintergrund das Image bauen. Bis jetzt baut es fleißig. Vielleicht würde ja ein setze_rootpwd_Hook helfen.

**Comment by gerdg-dd** [comment]
so, hab "user" zur Gruppe lpadmin hinzugefügt (https://github.com/fsfw-dresden/usb-live-linux/commit/0d78cd16e73662978397948546860c91ca165ae0) , der darf jetzt auch Drucker administrieren

**Comment by cknoll** [comment]
Ursache noch offen, aber Paket nicht unbedingt notwendig. Aktuell ist es auf -1. Problem damit nicht relevant.
