### ISSUE TITLE
Bootmenu überarbeiten (Persistenz als Standard)

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#62]
Da ja die Persistenz nun funktioniert und soviel Aufwand hierein gesteckt wurde, sollte sie auch verwendet werden. Ich fände es gut wenn _Persistenz_ die Standardeinstellung in einem vereinfachten Bootmenu wäre. (Ansonsten würde ich mir die _Failsafe_-Variante ohne Persistenz wünschen - beides wahlweise mit _toram_-Option und normal)

**Comment by cknoll** [comment]
Ich war ja derjenige, der darum gebeten hatte, die User nicht mit zu vielen Boot-Optionen zu verwirren.
Meine aktuelles Wunsch-Bootmenü sieht so aus:

---
Live-Linux mit Persistenz (Standard)
Live-Linux ohne Persistenz (Failsafe)

Tools / Weitere Optionen
---


*toram* würde ich persönlich für verzichtbar halten, kann meinetwegen aber unter weitere Optionen stehen.

**Comment by cknoll** [comment]
Am besten wäre eine Warnung im Skript wenn Persistenz-Partition zu klein ist.

**Comment by gerdg-dd** [comment]
erledigt mit  --> https://github.com/fsfw-dresden/usb-live-linux/commit/831d17ceb62f108d08301ac4da5ed9725366b5ca
