### ISSUE TITLE
Verzeichnisstruktur des Repos

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#63]
Um die Wahrscheinlichkeit zu erhöhen, dass andere was mit diesem Repo anfangen können sollte es eine klar verständliche Verzeichnisstruktur aufweisen. Der aktuelle Stand ist historisch gewachsen, aber nicht besonders intuitiv.

**Comment by cknoll** [comment]
@gerdg-dd 
Warum liegt src_fsfw-user_config jetzt in /doc/...?

Ich finde, da lag vorher schon zu viel Kram rum, der nicht zur Doku gehört...

**Comment by gerdg-dd** [comment]
In gewisser weise gehört es nach meiner Meinung schon dorthin, es enthält (fast alle) speziellen Einstellungen und zusätzliche Erweiterungen für die fsfw-user Konfiguration 
Frage: Wo könnte / sollte es den sonst hin ?

**Comment by cknoll** [comment]
Ich mache demnächst mal einen Vorschlag, wie ich mir die Verzeichnisstruktur des repos wünschen würde. vielleicht in einer markdown-Datei. Im Moment gibt es aber wichtigeres

**Comment by cknoll** [comment]
Wir (hauptsächlich @gerdg-dd und @cknoll) haben in den letzten Wochen einen Entwurf auf Papier gemacht, den wir inzwischen schrittweise umsetzten.

**Comment by Nos-** [comment]
ist dieser Issue noch aktuell? Schließlich wurde das Nachfolgeticket  #120 schon geschlossen.
