### ISSUE TITLE
user config

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#64]
Beim letzten Test (96q) hat noch folgendes gefehlt:
- [x] jupyter config
- [x] zim config
- [x] texstudio config (ohne die baut die Vorlage nicht richtig (Lit.Verz. braucht biber))
- [x] bashrc

das hängt eng zusammen mit #12 
@gerdg-dd da sollten wir zusammen abstimmen

**Comment by gerdg-dd** [comment]
texstudio Vorlage funktioniert bei mir im Test (96q) ?? ( geöffnet über Link in der Doku -- TeXstudio wird geladen --> PDF wird erstellt )

**Comment by cknoll** [comment]
Bei meinem letzten Test (ich glaube auch 96q) hat das Literaturverzeichnis nicht funktioniert, weil das mit "biber" gebaut wird. Es gab also nicht nur Warnmeldungen sondern Fehlermeldungen.

**Comment by gerdg-dd** [comment]
Habe gerade festgestellt ist ..config/includes.chroot/home/user nicht vorhanden werden Configurationsdatein auch aus config/includes.chroot/etc/skel übernommen.
Ist ../home/user vorhanden wird ../etc/skel ignoriert.
--> es scheint keine gute Idee zu sein ..config/includes.chroot/home/user anzulegen / zu benutzen
--> user configs sollten also nach config/includes.chroot/etc/skel

**Comment by cknoll** [comment]
aktueller Stand bei mir (branch ck_user-config): es geht alles zu meiner Zufriedenheit. Muss aber noch mit aktuellem master gemergt werden (wegen /etc/skel).

Dann muss vermutlich noch der jupyter hook angepasst werden (am besten nochmal separat /etc/skel/.jupyter ins home kopieren und Berechtigungen anpassen.)

**Comment by cknoll** [comment]
Problem: Laut log Datei wird der jupyter hook ausgeführt, wenn es noch kein /home/user gibt.
Durch das rsync im hook wird das Verzeichnis angelegt. Dadurch wird der Rest von  /etc/skel nicht ins Home-Verzeichnis kopiert.

Vorschlag: wir machen das selbst. Komplett mit rsync.

**Comment by gerdg-dd** [comment]
@cknoll mit FSFW_UNI_STICK_VERSION = 100a 
(https://github.com/fsfw-dresden/usb-live-linux/commit/7bdc8179145564aae62607c5fd2b286fcd602586)
hat es bei mir korrekt gebaut und die configs aus ../etc/skel sind alle da, auch /.jupyter/...
- nur die Desktopverknüpfung jupyter-ipython-notbook startet den Firefox noch nicht automatisch

- vielleicht können wir uns das mit dem sparaten hook ja sparen, im Moment scheint es ja gut auszusehen - weitere Tests folgen, braucht halt seine Zeit

**Comment by gerdg-dd** [comment]
Um für alle "user" verfügbar zu sein könnte das FSFW-Material eventuell auch nach /usr/share/doc/FSFW-Material  und wir arbeiten mit Links.

**Comment by gerdg-dd** [comment]
texstudio + muster-vorlage liefert noch ein einen Fehler siehe im Log
Bad Box Zeile 303 Underfull \hbox (badness 1048) in parograph
- Was fehlt da noch ?  ( an der config allein scheint es nicht zu liegen )

**Comment by cknoll** [comment]
Eine BadBox ist kein wichtiger Fehler (Wichtigkeit unterhalb einer Warnung.) Das kommt zustande, wenn LaTeX irgendwo dazu gezwungen ist über einen Rand rauszuschreiben, wenn auch nur um einen µm.

Ich baue gerade nochmal neu ohne separates jupyter-rsync.

**Comment by gerdg-dd** [comment]
Folgender Inhalt für " texstudio.ini" scheint völlig ausreichend zu sein.
[texmaker]
Tools\Commands\bibliography=txs:///biber

**Comment by cknoll** [comment]
@gerdg-dd wie es aussieht haben wir teilweise an den gleichen Dingen gearbeitet, aber Du warst schneller. Aktueller Stand bei mir alles (getestete) funktioniert wie es sollte (firefox Bookmarks, ipython start Verknüpfung, texstudio). Als ich jetzt nach master mergen wollte gab es Konflikte. Ich habe sie jetzt manuell behoben. Dieser Stand ist im branch ck_user-config3.

**Bitte erstmal (bis vermutlich Donnerstag Nachmittag) nicht mehr nach master pushen.**

**Comment by cknoll** [comment]
Ich Antworte hier mal auf die Kommentare von @gerdg-dd zu meinem letzten Commit, siehe
https://github.com/fsfw-dresden/usb-live-linux/commit/0b73904a3841980e882a46991f1ac0e9129ac760#commitcomment-19674695.


> fsfw-uni-stick_build.sh soltte nicht komplett als root laufen
Ich war/bin da anderer Meinung. Es gab irgendwelche Berechtigungsprobleme (wir hatten am Telefon drüber gesprochen, die Details habe ich jetzt aber auch nicht mehr im Kopf) und Nachfragen, ob die Paketlisten gelöscht werden können. Am Ende wollte sudo z.B. nochmal das Passwort haben.

Für mich ist wichtig, dass der build-Prozess ohne manuelle Intervention abläuft. Anstoßen, mich um andere Sachen kümmen, und 1h später ist die ISO fertig. Und da habe ich gute Erfahrungen gemacht, das komplette Skript als root bzw. mit sudo zu starten. Ich sehe nichts, was dagegen spricht. (Das heißt aber nicht, dass es keine Gegenargumente gibt.)

+1 zum Dokumentationsvorschlag.

Aber hier sollten wir konzeptuell zwischen zwei Zielgruppen unterscheiden.
1. Endanwender_innen: die interessiert nur der Ist-Stand und nicht so sehr was sich geändert hat.
2. Entwickler_innen (bisher nur wir): die interessiert eher was sich geändert hat.

Vorschläge
doc/src/fsfw-user-einstellungen.md
doc/src/change-notes.md

Außerdem sollten wir beachten, dass Dokumentation auch immer Arbeit macht. Es gilt ein gutes Maß zu finden.

**Comment by gerdg-dd** [comment]
fsfw-user doku - können wir das nicht in eine Datei packen ?
ähnlich FSFW-Uni-Stick_-_Paketliste.md - 
z.B.:

Taste Alt+F10 - xx Programm startet
[//]: # Komentar - ..ist in konfiguriert in  program.ini - config Zeile: Taste Alt+F10=/usr/bin/xx

--

TeXstudio - wir verwenden Biber
[//]: #  ~./config/texstudio/texstudio.ini 
[//]: #    [texmaker]
[//]: #    Tools\Commands\bibliography=txs:///biber

--
Wie die *.html generiert wir hab ich mir jetzt nicht angeschaut - werden Kommentare weggelassen ?

**Comment by cknoll** [comment]
Habe gerade meine Änderungen der letzten Tage nach Master gemergt. d.h. ich gebe den Master wieder frei.

@gerdg-dd 
Die MD-Kommentare sollten eigentlich beim Bauen der HTML-Doku ignoriert werden. Wenn wir das so machen habe ich nichts dagegen. Eigentlich ist das ein separates Issue aber das das hoffentlich schnell geht.. lohnt es vermutlich nicht ein neues aufzumachen.

Mein aktueller Favorit für den Dateinahme:

doc/src/konfigurationsanpassungen.md

**Comment by Nos-** [comment]
Seitdem ich pandoc installiert habe scheint nun auch die Info für Endanwender, die beim Starten automatisch im Browser geöffnet wird, zu funktionieren. Hat sonst noch jemand etwas?

**Comment by gerdg-dd** [comment]
Ist hier noch was zu erledigen ?
Ich wäre für schließen.

**Comment by cknoll** [comment]
zuletzt ging jupyter nicht. ich bin aber dran.

**Comment by Nos-** [comment]
@cknoll , hast du jupyter nochmal getestet? Funktioniert es?

Hat sonst noch jemand etwas?

**Comment by cknoll** [comment]
Ja. seit commit dc5f87936a4391c2d0075f55b9061d6c01724ad7 sollte es funktionieren. also im aktuellen develop und release-0.1.1 Zweig.
