### ISSUE TITLE
Inkrementelle Änderungen einfacher Testen

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#65]
Wir sollten herausfinden, ob es eine Möglichkeit gibt, das zeitaufwendige Neubauen des ganzen Images zu umgehen, wenn man nur ein paar Details ändern will.

Problem ist vermutlich das squash-Dateisystem. Vielleicht gibt es dazu eine Alternative? Man müsste vielleicht mal auf der Mailingliste fragen.

**Comment by Nos-** [comment]
Ist ein Duplikat von #67 .
