### ISSUE TITLE
Imageerstellungsprozess beschleunigen

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#67]
Selbst für kleinste Änderungen ist aktuell ein kompletter Buildprozess nötig, der jedesmal ca. 30-45 Min. braucht. Eine Verkürzung dieser Zeit (und vielleicht auch unnötiger Rechenaufwand) würden eine erhebliche Verbesserung darstellen.

Zwar werden bereits die verwendeten Softwarepakete gecached (oder gar durch lokale Repos/ Mirrors vorgehalten), dennoch bleibt ihre Zusammenstellung in einer chroot-Umgebung und vor allem die Erstellung eines (nachträglich nicht mehr änderbaren) Squash-Fs fürs Live-Image.

Würde man in einem dieser Schritte, etwa der zeitraubenden Erstellung des Squash-Fs - ansetzen, sollte ein erhebliches Verbesserungspotenzial drin sein.

**Comment by Nos-** [comment]
@gerdg-dd, wäre hier vielleicht ein Overlay-Fs oder Au...-Fs hilfreich?

**Comment by gerdg-dd** [comment]
Ich hätte es auch gern einfacher und schneller, aber
overlayfs wird glaub ich erst ab stretch unterstützt 

lb config --help --> 
--chroot-filesystem ( ext2|ext3|ext4|squashfs|jffs2|none )
- es sind auch nicht alle Filesysteme mit allen --binary-images (iso|iso-hybrid|netboot|tar|hdd) nutzbar
und --bootloader ( grub|syslinux ) muss auch noch passen

Die jetzige Kombination **iso-hybrid - squashfs - grub** fand ich funktionierte am besten

Es können gerne alle mittesten und funktionierende Kombiationen finden.

Bitte funktionierende Kombinationen dokumentieren, vielleicht unter
https://wiki.fsfw-dresden.de/doku.php/doku/usb-stick/debian_live-build

**Comment by cknoll** [comment]
Nach aktuellem Kenntnisstand scheint es hier keine Lösung zu geben. D.h. wir müssen auch für kleine inkrementelle Änderungen immer ein neues Image bauen...
