### ISSUE TITLE
src_fsfw-user_config/.gitconfig

### ISSUE THREAD

**Issue by gerdg-dd** [fsfw-dresden/usb-live-linux#68]
bin mir nicht sicher ob das mit der 

email = user0815@fsfw-uni-stick-live-linux.de

wirklich eine gute Idee ist ?

**Comment by cknoll** [comment]
Hintergrund ist, dass man im Entwicklungsprozess auf der VM einfach und
schnell git benutzen kann (z.B. um zusehen welche Dateien sich ändern)


Mir ist ziemlich egal welche (Fake)-Mailadresse da drin steht.
Hauptsache git commit funktioniert sofort.

**Comment by gerdg-dd** [comment]
ok - würde das aber trotzdem mal auf @localhost ändern (RFC2606)
