### ISSUE TITLE
Beispiel für tools/extra-install_paket.sh gewünscht

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#69]
Ich würde gern die extra-install_paket.sh aus dem tools-Verzeichnis nutzen, habe aber leider kein Beispiel finden können. Eine Ergänzung dessen wäre - auch im Sinne der Doku für andere - sicher hilfreich.

**Comment by gerdg-dd** [comment]
siehe Kommentar (https://github.com/fsfw-dresden/usb-live-linux/issues/53#issuecomment-257980811 )

--> https://github.com/fsfw-dresden/usb-live-linux/blob/master/doc/FSFW-Uni-Stick_-_Paketliste.md
Zeile 33 + 316

**Comment by Nos-** [comment]
Danke, da hätte ich mich ja gestern gar nicht mit Apt-pinning & Co. auseinandersetzen brauchen.
Nun denn, mein Ergebnis gibts in Kürze im Branch *ns_ZoteroPerDeb*
