### ISSUE TITLE
Firefox-Konfig

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#70]
Gibts Wünsche für bestimmte Einstellungen wie z.B.:

* Lesezeichen
  * ich würde gern einen Link zur [Wikiversity](https://www.wikiversity.org/) setzten, wenn nichts dagegenspricht
* vorinstallierte [Zitierstile](https://www.zotero.org/styles/) (im Zotero-Plugin, welches der Quellen- und Zitateverwaltung dient)
  * [welche Zitierstile sind den an der TU Dresden](https://www.zotero.org/styles/?q=Dresden) so üblich?

**Comment by Nos-** [comment]
Achja, der noch zu behebende Schönheitsfehler in Issue #53, zwecks Deaktivierung der Zotero-Startseite beim ersten Start, sollte somit auch erledigt sein.

**Comment by Nos-** [comment]
So, ich habe nun auch eingestellt, das MailTo-Links standardmäßig mit Icedove geöffnet werden sollen.

**Comment by Nos-** [comment]
Hier nun eine kleine Zusammenfassung der getätigten Änderungen (siehe auch Commitmessages):

* Bookmarks
* Mailto-Links mit Icedove öffnen lassen
* Konfig des Zotero-Plugins (Zitierstile der Dresdner Hochschulen)

**Comment by Nos-** [comment]
Issue #53 (Firefox-Plugins (Literaturverwaltung & Co.) ) ist leider nach wie vor ein Problem (naja wenigstens ein Schönheitsfehler).

Auch wenn das Repo mit seinen mittlerweile recht zahlreichen Feature-Branches und dem Bereinigen der des Firefox-Konfig-Ordners etwas umgegraben wurde, gibts immer noch das ein oder andere zum Nachbessern.

**Comment by Nos-** [comment]
Der Workaround für Issue #53 (Firefox-Plugins (Literaturverwaltung & Co.) ) sollte erstmal helfen.

**Comment by Nos-** [comment]
In Zeiten von Firefox > 60 ändert sich so einiges im Webbrowser. Selbst alte Addons werden i.d.R. nicht mehr unterstützt. Ich würde mich deshalb gern vom alten Firefox-Profil trennen und fände es gut die Browserkonfig neuzumachen.

**Comment by eMPee584** [comment]
:heavy_check_mark: ist neu gemacht => https://github.com/fsfw-dresden/usb-live-linux/blob/master/features/config_firefox-esr/livefs-include/usr/share/firefox-esr/distribution/policies.json
