### ISSUE TITLE
Falsch übersetzter Link in der Anwender-Doku/ Begrüßungsseite

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#74]
Bei automatisierten übersetzen der Links aus den Markdown-Quelldateien in Html-Dateien werden leider auch externe Links von .md zu .html geändert wodurch sie dann nicht mehr funktionieren.

Aufgefallen ist es mir beim Link auf unsere Softwareliste im Github. Statt https://github.com/fsfw-dresden/usb-live-linux/blob/master/doc/FSFW-Uni-Stick_-_Paketliste.md heißt es dort: https://github.com/fsfw-dresden/usb-live-linux/blob/master/doc/FSFW-Uni-Stick_-_Paketliste.html

Die betreffende [Markdown-Quelldatei](https://github.com/fsfw-dresden/usb-live-linux/blob/master/doc/src/index.md) ist in Ordnung und die Konvertierung der Dateiendungen auch, solange die betreffenden Dateien ebenfalls von Markdown nach Html konvertiert werden.

**Comment by cknoll** [comment]
Das Problem liegt in diesemPerl-Ersetzungs-Befehl-Ausdruck: https://github.com/fsfw-dresden/usb-live-linux/blob/master/tools/fsfw-user_config.sh#L62

`perl -p -i -e 's/\.md">/\.html">/g' $TARGETFILE`

**Comment by gerdg-dd** [comment]
sollte eigentlich jetzt funktionieren --> schließen
