### ISSUE TITLE
master branch im repo aufräumen

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#75]
Nach Ansicht der Gruppenmehrheit wurde der zotero Zweig zu früh nach master gemerged. Darin befanden / befinden sich noch zu viele automatisch erstellte Binärdateien.

Lösungsvorschlag: mit `git push -f`wird der master Zweig auf den letzten Kommit zurückgesetzt, der nichts mit zotero zu tun hat. Der alte master Zweit (mit den zotero Kommits) ist unter https://github.com/fsfw-dresden/usb-live-linux/tree/ex-master-zotero verfügbar.

Empfehlungen, um lokales Repo wieder synchron zu halten/kriegen
- erstmal sollte niemand mehr nach master commiten (und damit auch nicht pushen), bis nicht alle vier ihre repo synchronisiert haben, sodass db0eca475dd der HEAD von master ist.
- das kriegt man so hin: `git pull` danach `git reset --hard db0eca475dd`
- ggf. mit `git rebase ...` [(tutorial)](http://rypress.com/tutorials/git/rebasing) lokal commits in neue branches schieben
- mit `gitk --all` die Übersicht behalten.

**Comment by Nos-** [comment]
Hmm,
es ist bestimmt der Firefox-Konfig-Branch gemeint, den besagten Zotero-Branch kann ich nicht finden.

Eine Zusammenfassung der relevanten Firefox-Konfigs habe ich im Issue #70 zusammengetragen. Vielleicht hilft aber auch Cherry-picking.

**Comment by cknoll** [comment]
Der oben skizzierte Vorschlag wurde im November von mir umgesetz. Der daraus resultierende Zweig ex-master-zotero wurde seit dem nicht mehr verändert. Ich betrachte ihn als obsolet und werde ihn jetzt (im Rahmen des Aufräumen des Repos) löschen. Damit gehen ja keine inhaltlichen Änderungen verloren (die im originalen Firefox-Branch stecken). Falls der Zweig ex-master-zotero trotzdem noch mal relevant werden sollte: Ich habe noch eine lokale Kopie, die ich bis mindestens Ende März aufhebe.
