### ISSUE TITLE
icedove vs. thunderbird

### ISSUE THREAD

**Issue by s72785** [fsfw-dresden/usb-live-linux#8]
{als ich grad den screenshot sah…}

Ich weiß es macht keinen echten Unterschied. Aber die Trennung soll ja zeitnah aufgehoben werden und ggf. verwirrt das neune Nutzer eher (bei Windows haben sie auch TB) als alles andere – kann man schon heute Thunderbird statt Icedove auf debian konfigurieren? Auch ohne das dann z.B. Doppelinstallationen auftreten.

Wenns zu kompliziert ist, dann eben erstmal so lassen.

**Comment by Nos-** [comment]
Naja, Iceweasel ist in #7 bereits durch Firefox ESR ersetzt. Nur Icedove -> Thunderbird könnte etwas aufwendiger werden.

**Comment by Nos-** [comment]
Als einfachen Kompromiss möchte ich vorschlagen Icedove zu verwenden und in der Doku einen Satz dazu reinzuschreiben (warum der Namensunterschied Icedove und Mozilla Thunderbird). (Falls gewünscht könnte man auch den Menüeintrag ändern, sodas er beide Namen enthält.)

**Comment by cknoll** [comment]
Doku angepasst, siehe 

https://github.com/fsfw-dresden/usb-live-linux/commit/21bd19f3520b4896733f3849b040e8485606f6c7 
und https://github.com/fsfw-dresden/usb-live-linux/commit/9b7387675c73a3dbadc460c1ae43d5d04c44f802.
