### ISSUE TITLE
Erstellte .ISO-Datei sollte Branchnamen im Namen tragen

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/usb-live-linux#82]
Wer kennt es nicht. man arbeitet an verschiedenen Features - natürlich in separaten Branches - und möchte die erstellten Iso-Images zwecks Vergleich testen. Doch leider ist am Dateinamen nicht erkennbar, welches Iso zu welchem Branch gehört.

Aus diesem Grund bin ich dafür das Skript, welches die Namen der Iso-Dateien festlegt, um den Git-Branchnamen zu erweitern.

**Comment by cknoll** [comment]
klingt sinnvoll.

**Comment by gerdg-dd** [comment]
in ../auto/config
kannst du dafür die Zeile 
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}_${DISTRIBUTION} \
anpassen

**Comment by Nos-** [comment]
Besten Dank @gerdg-dd .
