### ISSUE TITLE
Hintergrundbild sollte passend skalieren. Bei 4:3 kommen schwarze Balken

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/usb-live-linux#92]

**Comment by gerdg-dd** [comment]
Hallo,
dafür kann ab Debian stretch
https://github.com/fsfw-dresden/usb-live-linux/tree/develop/config/FSFW-Uni-Stick_KDE_stretch_amd64/system_config/includes.chroot/usr/share/desktop-base/fsfw-theme
angepasst werden

VG Gerd
